export const ERR = {
  BAD_REQUEST: 'BAD_REQUEST',
  CANNOT_CREATE_AUTHOR: 'CANNOT_CREATE_AUTHOR',
  CANNOT_UPDATE_AUTHOR: 'CANNOT_UPDATE_AUTHOR',
  CANNOT_DELETE_AUTHOR: 'CANNOT_DELETE_AUTHOR',
  CANNOT_CREATE_SONG: 'CANNOT_CREATE_SONG',
  CANNOT_UPDATE_SONG: 'CANNOT_UPDATE_SONG',
  CANNOT_DELETE_SONG: 'CANNOT_DELETE_SONG'
}